modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU-AGPL-3.0-only"
[[mods]]
modId = "spotting"
version = "${file.jarVersion}"
displayName = "Spotting"
authors = [
    "Tapio",
    "MUYU_Twilighter"
]
description = ""
credits = '''

Amazon Polly for builtin voices:
CV(English, Male) -> Matthew (AI)
CV(English, Female) -> Salli (AI)
'''